# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\"\x19\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\rUpdateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\" \n\rSearchRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\":\n\x0bKeyResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x80\x01\n\x0eSearchResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.SearchResponse.ResultsEntry\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a.\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"+\n\rPutKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x8a\x02\n\rKeyValueStore\x12#\n\x06GetKey\x12\x0b.KeyRequest\x1a\x0c.KeyResponse\x12)\n\tUpdateKey\x12\x0e.UpdateRequest\x1a\x0c.KeyResponse\x12&\n\x06PutKey\x12\x0e.PutKeyRequest\x1a\x0c.KeyResponse\x12&\n\tDeleteKey\x12\x0b.KeyRequest\x1a\x0c.KeyResponse\x12,\n\tSearchKey\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\x12+\n\x0eInternalDelete\x12\x0b.KeyRequest\x1a\x0c.KeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHRESPONSE_RESULTSENTRY']._loaded_options = None
  _globals['_SEARCHRESPONSE_RESULTSENTRY']._serialized_options = b'8\001'
  _globals['_KEYREQUEST']._serialized_start=17
  _globals['_KEYREQUEST']._serialized_end=42
  _globals['_UPDATEREQUEST']._serialized_start=44
  _globals['_UPDATEREQUEST']._serialized_end=87
  _globals['_SEARCHREQUEST']._serialized_start=89
  _globals['_SEARCHREQUEST']._serialized_end=121
  _globals['_KEYRESPONSE']._serialized_start=123
  _globals['_KEYRESPONSE']._serialized_end=181
  _globals['_SEARCHRESPONSE']._serialized_start=184
  _globals['_SEARCHRESPONSE']._serialized_end=312
  _globals['_SEARCHRESPONSE_RESULTSENTRY']._serialized_start=266
  _globals['_SEARCHRESPONSE_RESULTSENTRY']._serialized_end=312
  _globals['_PUTKEYREQUEST']._serialized_start=314
  _globals['_PUTKEYREQUEST']._serialized_end=357
  _globals['_KEYVALUESTORE']._serialized_start=360
  _globals['_KEYVALUESTORE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
