# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kvstore_pb2 as kvstore__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kvstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKey = channel.unary_unary(
                '/KeyValueStore/GetKey',
                request_serializer=kvstore__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvstore__pb2.KeyResponse.FromString,
                _registered_method=True)
        self.UpdateKey = channel.unary_unary(
                '/KeyValueStore/UpdateKey',
                request_serializer=kvstore__pb2.UpdateRequest.SerializeToString,
                response_deserializer=kvstore__pb2.KeyResponse.FromString,
                _registered_method=True)
        self.PutKey = channel.unary_unary(
                '/KeyValueStore/PutKey',
                request_serializer=kvstore__pb2.PutKeyRequest.SerializeToString,
                response_deserializer=kvstore__pb2.KeyResponse.FromString,
                _registered_method=True)
        self.DeleteKey = channel.unary_unary(
                '/KeyValueStore/DeleteKey',
                request_serializer=kvstore__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvstore__pb2.KeyResponse.FromString,
                _registered_method=True)
        self.SearchKey = channel.unary_unary(
                '/KeyValueStore/SearchKey',
                request_serializer=kvstore__pb2.SearchRequest.SerializeToString,
                response_deserializer=kvstore__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.InternalDelete = channel.unary_unary(
                '/KeyValueStore/InternalDelete',
                request_serializer=kvstore__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvstore__pb2.KeyResponse.FromString,
                _registered_method=True)


class KeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=kvstore__pb2.KeyRequest.FromString,
                    response_serializer=kvstore__pb2.KeyResponse.SerializeToString,
            ),
            'UpdateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKey,
                    request_deserializer=kvstore__pb2.UpdateRequest.FromString,
                    response_serializer=kvstore__pb2.KeyResponse.SerializeToString,
            ),
            'PutKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PutKey,
                    request_deserializer=kvstore__pb2.PutKeyRequest.FromString,
                    response_serializer=kvstore__pb2.KeyResponse.SerializeToString,
            ),
            'DeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKey,
                    request_deserializer=kvstore__pb2.KeyRequest.FromString,
                    response_serializer=kvstore__pb2.KeyResponse.SerializeToString,
            ),
            'SearchKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKey,
                    request_deserializer=kvstore__pb2.SearchRequest.FromString,
                    response_serializer=kvstore__pb2.SearchResponse.SerializeToString,
            ),
            'InternalDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalDelete,
                    request_deserializer=kvstore__pb2.KeyRequest.FromString,
                    response_serializer=kvstore__pb2.KeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('KeyValueStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyValueStore/GetKey',
            kvstore__pb2.KeyRequest.SerializeToString,
            kvstore__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyValueStore/UpdateKey',
            kvstore__pb2.UpdateRequest.SerializeToString,
            kvstore__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyValueStore/PutKey',
            kvstore__pb2.PutKeyRequest.SerializeToString,
            kvstore__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyValueStore/DeleteKey',
            kvstore__pb2.KeyRequest.SerializeToString,
            kvstore__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyValueStore/SearchKey',
            kvstore__pb2.SearchRequest.SerializeToString,
            kvstore__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InternalDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyValueStore/InternalDelete',
            kvstore__pb2.KeyRequest.SerializeToString,
            kvstore__pb2.KeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
